### ISSUE TITLE
Nächstens Event planen

### ISSUE THREAD

**Issue by Akendo** [Security-Nights/orga#3]
- [x] Einen neuen Termin für die Security Night finden
- [x] Präsentationen suchen

**Comment by Akendo** [comment]
Wir haben uns auf den 02.03.2023 geeinigt und gleichen den Termin mit den Vortragenden ab.

**Comment by mgfalkus** [comment]
> Wir haben uns auf den 02.03.2023 geeinigt und gleichen den Termin mit den Vortragenden ab.

Dieser Termin ist mit der c-base abgestimmt, nor? Im Kalender steht noch nix...

Vorschlag fuer eine Bezeichnung: "Security Night 2023/March"

**Comment by Akendo** [comment]
Klingt gut. Mit der Ankündigung werden wir eine E-Mail an die cultorga der c-base schreiben. GGf. müssen wir mit den Leuten von den diversen Stammtischen sprechen.

![image](https://user-images.githubusercontent.com/1384917/217516406-ba54dd24-778e-46e9-9f3c-281b4341156b.png)

**Comment by Akendo** [comment]
Hups flasches Datum selber Veranstaltung.

**Comment by mgfalkus** [comment]
> Klingt gut. Mit der Ankündigung werden wir eine E-Mail an die cultorga der c-base schreiben. GGf. müssen wir mit den Leuten von den diversen Stammtischen sprechen.
> 
> [...]

Hier der 02.03.: [click](https://c-base.org/calendar/#view=month&date=2023-03-01&event=985bc712-a766-4198-bd62-a5a59a93c3bc-35)

@Akendo: Also muessen wir vorher noch all diese Stammtische mit ins Boot holen?

**Comment by Akendo** [comment]
> @Akendo: Also muessen wir vorher noch all diese Stammtische mit ins Boot holen?

Meines Verständnisse nicht. Ich habe Bescheid gegeben und der Verantwortliche Member in der c-base spricht mit den jeweiligen Veranstaltenden. Im ganz gilt dieser Termin als Platzhalter, um Leuten einen Anlaufpunkt zu bieten. 

Sobald wir die Einladung geschrieben habe, leite ich diese weiter an cultorger und es wird in den Kalender der c-base geschrieben. 

Falls es zu Konflikten kommen wird, sollten wir Bescheid bekommen.
